package ma.gbp.objectif.gestion.model.authentification;

public enum Droit {
	P_NOUVELLE_DEMANDE,
	P_AFFECTER_TACHE_INSTRUCTION,
	P_AFFECTER_TACHE_ETUDE,
	P_DOSSIER,
	P_AGENCE,
	P_SUCCURSALE,
	P_BPR,
	P_ACCORDEE_DASHBOARD,
	P_REJETEE_DASHBOARD,
	P_ACCORDEE_DOSSIER,
	P_REJETEE_DOSSIER,
}
